### PR TITLE
Adds url to automatic definition writing

### PR DESCRIPTION
**Pull request by domna**
This adds that `entry/definition/@url` is automatically set to the nexus definitions repo. We also set this in the root attribute `NexusRepository` but @RonHildebrandt and I thought it would be reasonable to also automatically add it to the definition.

In `NXentry` the attribute is actually uppercase (`@URL`) so we might need to change this accordingly. @RonHildebrandt this should then also be changed in NXraman and any appdefs this is required in.

### CODE REVIEW

**Comment by domna** [comment]
cc @RubelMozumder @lukaspie, you would need to update the stm and xps regression files for this change to pass the tests

**Comment by lukaspie** [comment]
> cc @RubelMozumder @lukaspie, you would need to update the stm and xps regression files for this change to pass the tests

I have a branch https://github.com/FAIRmat-NFDI/pynxtools-xps/pull/67 that updates the test files (and which works with this branch here, check the pynx compatibility action), but then the pytest actions in pynxtools-xps are failing (because it checks against released pynxtools). What would be the best strategy here? Merge this branch here with the plugin tests failing and then we do the changes in the plugin repos?

**Comment by lukaspie** [comment]
> > > cc @RubelMozumder @lukaspie, you would need to update the stm and xps regression files for this change to pass the tests
> > 
> > 
> > I have a branch [FAIRmat-NFDI/pynxtools-xps#67](https://github.com/FAIRmat-NFDI/pynxtools-xps/pull/67) that updates the test files (and which works with this branch here, check the pynx compatibility action), but then the pytest actions in pynxtools-xps are failing (because it checks against released pynxtools). What would be the best strategy here? Merge this branch here with the plugin tests failing and then we do the changes in the plugin repos?
> 
> Yes, I would say so. We should probably coordinate the merges and then do it quickly after each other

Ok, from my side, it works, so just let me know when you merge this. I guess we would need @RubelMozumder to update his test data first.

**Comment by domna** [comment]
> > > > cc @RubelMozumder @lukaspie, you would need to update the stm and xps regression files for this change to pass the tests
> > > 
> > > 
> > > I have a branch [FAIRmat-NFDI/pynxtools-xps#67](https://github.com/FAIRmat-NFDI/pynxtools-xps/pull/67) that updates the test files (and which works with this branch here, check the pynx compatibility action), but then the pytest actions in pynxtools-xps are failing (because it checks against released pynxtools). What would be the best strategy here? Merge this branch here with the plugin tests failing and then we do the changes in the plugin repos?
> > 
> > 
> > Yes, I would say so. We should probably coordinate the merges and then do it quickly after each other
> 
> Ok, from my side, it works, so just let me know when you merge this. I guess we would need @RubelMozumder to update his test data first.

Jep, I also need to update it for mpes. But lets wait and coordinate with @RubelMozumder (probably tomorrow since he has internet issues today)

**Comment by RubelMozumder** [comment]
> > > > > cc @RubelMozumder @lukaspie, you would need to update the stm and xps regression files for this change to pass the tests
> > > > 
> > > > 
> > > > I have a branch [FAIRmat-NFDI/pynxtools-xps#67](https://github.com/FAIRmat-NFDI/pynxtools-xps/pull/67) that updates the test files (and which works with this branch here, check the pynx compatibility action), but then the pytest actions in pynxtools-xps are failing (because it checks against released pynxtools). What would be the best strategy here? Merge this branch here with the plugin tests failing and then we do the changes in the plugin repos?
> > > 
> > > 
> > > Yes, I would say so. We should probably coordinate the merges and then do it quickly after each other
> > 
> > 
> > Ok, from my side, it works, so just let me know when you merge this. I guess we would need @RubelMozumder to update his test data first.
> 
> Jep, I also need to update it for mpes. But lets wait and coordinate with @RubelMozumder (probably tomorrow since he has internet issues today)

I update the pynxtools-stm, regarding the PR. @domna you can approve it and merge it. So, you will get any github action failing from `plugin_test` action.

**Comment by domna** [comment]
We need to use uppercase `@URL`, otherwise the concept is not recognised. @RonHildebrandt I think you should update this in your `NXoptical_spectroscopy` definition accordingly. @lukaspie Sorry, I think you need to do another update for your regression file to account for the uppercase notation.

Otherwise, we are just waiting on https://github.com/FAIRmat-NFDI/pynxtools-stm/pull/39 to coordinate the merges

**Comment by lukaspie** [comment]
> We need to use uppercase `@URL`, otherwise the concept is not recognised. @RonHildebrandt I think you should update this in your `NXoptical_spectroscopy` definition accordingly. @lukaspie Sorry, I think you need to do another update for your regression file to account for the uppercase notation.
> 
> Otherwise, we are just waiting on [FAIRmat-NFDI/pynxtools-stm#39](https://github.com/FAIRmat-NFDI/pynxtools-stm/pull/39) as the last merge which needs to be ready so we can do it quickly after each other.

No worries, I updated the pynxtools-xps branch one more.

**Pull request merged**
