### PR TITLE
Adding default group features.

### PR DESCRIPTION
**Pull request by RubelMozumder**
For adding the default group mentioned in issue: #255
Suggestion by @lukaspie in #250 

- [ ] Needs to be tested with nexus parser in nomad. Using @default for non-NXdata entries is problematic with NOMAD. (mentioned by @Florian)

### CODE REVIEW

**Comment by domna** [comment]
There was a problem with attaching `@default` attributes with @lukaspie's dataset. When parsing in NOMAD we got the following error:

```
ERROR    nomad.client         2024-04-05T15:12:05 parsing was not successful
  - exception: Traceback (most recent call last):
      File "C:\Users\pielsticker\Lukas\FAIRMat\code\nomad\nomad\parsing\parsers.py", line 215, in run_parser
        parser.parse(mainfile_path, entry_archive, logger=logger, **kwargs)
      File "C:\Users\pielsticker\Lukas\FAIRMat\code\nomad\nomad\parsing\parser.py", line 461, in parse
        self.mainfile_parser.parse(mainfile, archive, logger)
      File "C:\Users\pielsticker\Lukas\FAIRMat\code\nomad\nomad\parsing\nexus\nexus.py", line 352, in parse
        nexus_helper.process_nexus_master_file(self.__nexus_populate)
      File "C:\Users\pielsticker\Anaconda3\envs\nomad-testing2\lib\site-packages\pynxtools\nexus\nexus.py", line 744, in process_nexus_master_file
        get_default_plotable(self.in_file, self.logger)
      File "C:\Users\pielsticker\Anaconda3\envs\nomad-testing2\lib\site-packages\pynxtools\nexus\nexus.py", line 466, in get_default_plotable
        signal = signal_helper(nxdata)
      File "C:\Users\pielsticker\Anaconda3\envs\nomad-testing2\lib\site-packages\pynxtools\nexus\nexus.py", line 513, in signal_helper
        for key in nxdata.keys():
    AttributeError: 'Dataset' object has no attribute 'keys'
  - exception_hash: HXM2caARc_guAOuIAJwMnOn486r7
  - nomad.client.parser: parsers/nexus
  - nomad.commit:
  - nomad.deployment: devel
  - nomad.service: cli
  - nomad.version: 1.2.2.dev421+gff18c846b.d20240227
```

The problem was that there was a `NXdata` group which itself had a `@default`, so the parser tried to use this as default plotable. However, the default argument is not needed in `NXdata`, it can just be given with `@signal` and `@auxillary_signal`. Two options here: We fix it in `get_default_plotable` that we reject it properly in case we don't end up at an NXdata _or_ we _never_ write a `@default` inside an `NXdata` group.

I don't know if this error came also from attaching `@default` values which chains don't end at an `NXdata`, because we just removed every additional `@default` in the example dataset.

**Comment by RubelMozumder** [comment]
> There was a problem with attaching `@default` attributes with @lukaspie's dataset. When parsing in NOMAD we got the following error:
> 
> ```
> ERROR    nomad.client         2024-04-05T15:12:05 parsing was not successful
>   - exception: Traceback (most recent call last):
>       File "C:\Users\pielsticker\Lukas\FAIRMat\code\nomad\nomad\parsing\parsers.py", line 215, in run_parser
>         parser.parse(mainfile_path, entry_archive, logger=logger, **kwargs)
>       File "C:\Users\pielsticker\Lukas\FAIRMat\code\nomad\nomad\parsing\parser.py", line 461, in parse
>         self.mainfile_parser.parse(mainfile, archive, logger)
>       File "C:\Users\pielsticker\Lukas\FAIRMat\code\nomad\nomad\parsing\nexus\nexus.py", line 352, in parse
>         nexus_helper.process_nexus_master_file(self.__nexus_populate)
>       File "C:\Users\pielsticker\Anaconda3\envs\nomad-testing2\lib\site-packages\pynxtools\nexus\nexus.py", line 744, in process_nexus_master_file
>         get_default_plotable(self.in_file, self.logger)
>       File "C:\Users\pielsticker\Anaconda3\envs\nomad-testing2\lib\site-packages\pynxtools\nexus\nexus.py", line 466, in get_default_plotable
>         signal = signal_helper(nxdata)
>       File "C:\Users\pielsticker\Anaconda3\envs\nomad-testing2\lib\site-packages\pynxtools\nexus\nexus.py", line 513, in signal_helper
>         for key in nxdata.keys():
>     AttributeError: 'Dataset' object has no attribute 'keys'
>   - exception_hash: HXM2caARc_guAOuIAJwMnOn486r7
>   - nomad.client.parser: parsers/nexus
>   - nomad.commit:
>   - nomad.deployment: devel
>   - nomad.service: cli
>   - nomad.version: 1.2.2.dev421+gff18c846b.d20240227
> ```
> 
> The problem was that there was a `NXdata` group which itself had a `@default`, so the parser tried to use this as default plotable. However, the default argument is not needed in `NXdata`, it can just be given with `@signal` and `@auxillary_signal`. Two options here: We fix it in `get_default_plotable` that we reject it properly in case we don't end up at an NXdata _or_ we _never_ write a `@default` inside an `NXdata` group.
> 
> I don't know if this error came also from attaching `@default` values which chains don't end at an `NXdata`, because we just removed every additional `@default` in the example dataset.

This feature only refers to the group from a list of first-child groups. It does not consider any fields to be referenced to a group.
So, it never sets a default attribute to the NXdata, because NXdata would be a leaf group for an entry, that can not have any successive group right.
I added a test, please have a look at the test, If you think we can add more check points in this test.

**Comment by lukaspie** [comment]
> > There was a problem with attaching `@default` attributes with @lukaspie's dataset. When parsing in NOMAD we got the following error:
> > ```
> > ERROR    nomad.client         2024-04-05T15:12:05 parsing was not successful
> >   - exception: Traceback (most recent call last):
> >       File "C:\Users\pielsticker\Lukas\FAIRMat\code\nomad\nomad\parsing\parsers.py", line 215, in run_parser
> >         parser.parse(mainfile_path, entry_archive, logger=logger, **kwargs)
> >       File "C:\Users\pielsticker\Lukas\FAIRMat\code\nomad\nomad\parsing\parser.py", line 461, in parse
> >         self.mainfile_parser.parse(mainfile, archive, logger)
> >       File "C:\Users\pielsticker\Lukas\FAIRMat\code\nomad\nomad\parsing\nexus\nexus.py", line 352, in parse
> >         nexus_helper.process_nexus_master_file(self.__nexus_populate)
> >       File "C:\Users\pielsticker\Anaconda3\envs\nomad-testing2\lib\site-packages\pynxtools\nexus\nexus.py", line 744, in process_nexus_master_file
> >         get_default_plotable(self.in_file, self.logger)
> >       File "C:\Users\pielsticker\Anaconda3\envs\nomad-testing2\lib\site-packages\pynxtools\nexus\nexus.py", line 466, in get_default_plotable
> >         signal = signal_helper(nxdata)
> >       File "C:\Users\pielsticker\Anaconda3\envs\nomad-testing2\lib\site-packages\pynxtools\nexus\nexus.py", line 513, in signal_helper
> >         for key in nxdata.keys():
> >     AttributeError: 'Dataset' object has no attribute 'keys'
> >   - exception_hash: HXM2caARc_guAOuIAJwMnOn486r7
> >   - nomad.client.parser: parsers/nexus
> >   - nomad.commit:
> >   - nomad.deployment: devel
> >   - nomad.service: cli
> >   - nomad.version: 1.2.2.dev421+gff18c846b.d20240227
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The problem was that there was a `NXdata` group which itself had a `@default`, so the parser tried to use this as default plotable. However, the default argument is not needed in `NXdata`, it can just be given with `@signal` and `@auxillary_signal`. Two options here: We fix it in `get_default_plotable` that we reject it properly in case we don't end up at an NXdata _or_ we _never_ write a `@default` inside an `NXdata` group.
> > I don't know if this error came also from attaching `@default` values which chains don't end at an `NXdata`, because we just removed every additional `@default` in the example dataset.
> 
> This feature only refers to the group from a list of first-child groups. It does not consider any fields to be referenced to a group. So, it never sets a default attribute to the NXdata, because NXdata would be a leaf group for an entry, that can not have any successive group right. I added a test, please have a look at the test, If you think we can add more check points in this test.

We have to differentiate here between what was the problem in the config file of the XPS reader (i.e., the `NXdata` group itself had a `@default`, which it shouldn't have) and the general idea of adding `@default` to groups "by default (what is proposed here, sorry for the double use of default). The first has been solved already (both in the config and in what @domna wrote above) and NXdata itself shouldn't have a `@default` in general. 

The second idea is discussed here. I am not sure what the plan is, aka which sub-group will be set as default. If I have the following structure, what would be chosen for the two `@defaults` with the question marks, @RubelMozumder? Does it just take the first subgroup? Maybe a bit more documentation of the general logic would be helpful.
```yaml
/@default: ?? # I guess this would be entry0
/entry0:
  /entry0/@default: ??
  /entry0/subgroup0: # subgroup0?
  /entry0/subgroup1:
/entry1:
```

**Comment by RubelMozumder** [comment]
This PR is handled in #349.

**Pull request closed without merging**
