### PR TITLE
Fix branch in ci/cd in genric test

### PR DESCRIPTION
**Pull request by RubelMozumder**

### CODE REVIEW

**Review by lukaspie — APPROVED** [review]

**Review by lukaspie — CHANGES_REQUESTED** [review]
Actually, if we have
```yaml
on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]
```
the CI gets run twice when we have a PR to master.

So, I suggest replacing `branches: ["*"]` by `branches: [master]`, so that the CI only gets run 1) when there is a PR to master, or 2) on a push (be it a direct push or through a merge of a PR) to master.
```yaml
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
```

**Comment by RubelMozumder** [comment]
> Actually, if we have
> 
> ```yaml
> on:
>   push:
>     branches: ["*"]
>   pull_request:
>     branches: [master]
> ```
> 
> the CI gets run twice when we have a PR to master.
> 
> So, I suggest replacing `branches: ["*"]` by `branches: [master]`, so that the CI only gets run 1) when there is a PR to master, or 2) on a push (be it a direct push or through a merge of a PR) to master.
> 
> ```yaml
> on:
>   push:
>     branches: [master]
>   pull_request:
>     branches: [master]
> ```

Isn't it expected to see twice?
One is coming from the `feature` branch, another one is coming from the `master` branch due to the PR to `master` branch.

https://github.com/FAIRmat-NFDI/pynxtools/actions/runs/9269299202/job/25499817118?pr=336#step:2:554

Here, it checked out to the HEAD commit of the `feature` branch. If you still suggest to go back to the previous settings `[master]`, I can do it.

**Comment by lukaspie** [comment]
> > Actually, if we have
> > ```yaml
> > on:
> >   push:
> >     branches: ["*"]
> >   pull_request:
> >     branches: [master]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the CI gets run twice when we have a PR to master.
> > So, I suggest replacing `branches: ["*"]` by `branches: [master]`, so that the CI only gets run 1) when there is a PR to master, or 2) on a push (be it a direct push or through a merge of a PR) to master.
> > ```yaml
> > on:
> >   push:
> >     branches: [master]
> >   pull_request:
> >     branches: [master]
> > ```
> 
> Isn't it expected to see twice? One is coming from the `feature` branch, another one is coming from the `master` branch due to the PR to `master` branch.
> 
> https://github.com/FAIRmat-NFDI/pynxtools/actions/runs/9269299202/job/25499817118?pr=336#step:2:554
> 
> Here, it checked out to the HEAD commit of the `feature` branch. If you still suggest to go back to the previous settings `[master]`, I can do it.

The point is that with the current settings, it runs the same test twice when there's a PR to master (like this one here), which is not neccessary. Therefore, I suggest going back to `[master]`.

**Comment by RubelMozumder** [comment]
> CI is failing because there is no `TestFromPynxtools` branch available in pynxtools-stm.

Noted!

**Review by lukaspie — APPROVED** [review]

**Pull request merged**
