### PR TITLE
Pluginise mpes reader

### LINKED ISSUE #234: Pluginise mpes reader
We could also think about having a generic igor reader that we can then map for the different techniques.

### PR DESCRIPTION
**Pull request by domna**
The MPES reader is moving into its own plugin at https://github.com/FAIRmat-NFDI/pynxtools-mpes

Fixes #234

### CODE REVIEW

**Comment by domna** [comment]
@sherjeelshabih I removed all the mpes related tests and move this into the reader plugin. Do you think we need to recreate some tests for the example reader to cover functionality?

@rettigl This is mainly fyi. When everything is moved you need to do an additional `pip install pynxtools-mpes` and everything should be picked up automatically from there. I will also add this as an install extra as [mpes]

**Comment by lukaspie** [comment]
> @rettigl This is mainly fyi. When everything is moved you need to do an additional pip install pynxtools-mpes and everything should be picked up automatically from there. I will also add this as an install extra as [mpes]

That's a good idea also for the other plugins. Maybe we could also make an install extra as [all-readers] or something that install all plugins (at least the ones that we are aware of or for which we provide its own install extra)?

**Comment by domna** [comment]
> > @rettigl This is mainly fyi. When everything is moved you need to do an additional pip install pynxtools-mpes and everything should be picked up automatically from there. I will also add this as an install extra as [mpes]
> 
> That's a good idea also for the other plugins. Maybe we could also make an install extra as [all-readers] or something that installs all plugins (at least the ones that we are aware of or for which we provide its own install extra)?
> 

Yes, this is a good idea. We should have this for all plugins we support and I think it's also fine if people want to add their readers there.
> EDIT: I think in general it would be nice to also list the supported plugins in the pynxtools main repo somewhere (maybe also in README?)

Yes, maybe we can get the list from the [pynxtools-plugin](https://github.com/topics/pynxtools-plugin) topic. That way it would automatically update :) If not we can just keep a list but link to the topic.

**Comment by domna** [comment]
#247

**Comment by sherjeelshabih** [comment]
> @sherjeelshabih I removed all the mpes related tests and move this into the reader plugin. Do you think we need to recreate some tests for the example reader to cover functionality?

I'll have a look on what tests etc will be needed separately. You can keep this PR for dealing with the MPES reader. I'll make an issue to check test coverage again for the JOSS paper.

**Review by lukaspie — APPROVED** [review]
LGTM, will do the same for https://github.com/FAIRmat-NFDI/pynxtools-xps.

**Comment by rettigl** [comment]
I tested it, and it works, however this changes the functionality of pynxtools, so we should discuss how to adjust versioning accordingly (we are probably the only ones using the mpes reader right now, but the next version of pynxtools without extras definition will break the behavior).

**Comment by domna** [comment]
> I tested it, and it works, however this changes the functionality of pynxtools, so we should discuss how to adjust versioning accordingly (we are probably the only ones using the mpes reader right now, but the next version of pynxtools without extras definition will break the behavior).

Yes, we should follow proper semantic versioning for pynxtools to indicate when we introduce breaking changes. See #225. Ideally, we would now do the main changes until a v1.0.0 release so that we don't have to introduce breaking changes for a long time.

I would do a v0.1.0 release for the next version to indicate that we break something.

**Pull request merged**
