### PR TITLE
Small typo and docstring fixes

### PR DESCRIPTION
**Pull request by domna**
- Adds missing docstrings for `is_a` and `parent_of` relationships
- Fixes a typo and residual code in sibling retrieval
- Renames a function to correctly represent what it does

### CODE REVIEW

**Comment by lukaspie** [comment]
@domna shall I test this somehow with one of my own files? Or are you sure it's (still) working as intended?

**Comment by domna** [comment]
> @domna shall I test this somehow with one of my own files? Or are you sure it's (still) working as intended?

For the part changed here I'm sure that it does what it should. However, while testing this I found another bug and I would also bring the fix here (which only appears sometimes... so I wasn't quite aware from the start)

**Comment by lukaspie** [comment]
> > @domna shall I test this somehow with one of my own files? Or are you sure it's (still) working as intended?
> 
> For the part changed here I'm sure that it does what it should. However, while testing this I found another bug and I would also bring the fix here (which only appears sometimes... so I wasn't quite aware from the start)



> > @domna shall I test this somehow with one of my own files? Or are you sure it's (still) working as intended?
> 
> For the part changed here I'm sure that it does what it should. However, while testing this I found another bug and I would also bring the fix here (which only appears sometimes... so I wasn't quite aware from the start)

Alright, then just let me know once you have that fix and then I can test it.

**Comment by domna** [comment]
> Alright, then just let me know once you have that fix and then I can test it.

Should be fixed now

**Review by lukaspie — APPROVED** [review]
LGTM

**Pull request merged**
