### PR TITLE
Count readers onee if readers from reader package and pynxtools are c…

### PR DESCRIPTION
**Pull request by RubelMozumder**
Count readers once.

### CODE REVIEW

**Review by sherjeelshabih — COMMENTED** [review]
I wouldn't want to have duplicate readers. But I guess in the case where we do have two of the same named ones, showing the name(s) once is alright.

These changes are fine for me. I'll let @domna also have his comment. @domna , feel free to approve when you're happy.

**Comment by domna** [comment]
Actually, I came across the same problem and I decided not to do this fix.
If people have multiple readers it just goes unnoticed and they might not be aware that they are actually using another reader as they expect, which might have unforeseen consequences (wrongly produced data etc). So I would at least do an additional warning here or even error out as multiple readers of the same name should not be allowed as this should not happen too often and can simply be solved by uninstalling one of the reader plugins.

**Comment by sherjeelshabih** [comment]
> Actually, I came across the same problem and I decided not to do this fix. If people have multiple readers it just goes unnoticed and they might not be aware that they are actually using another reader as they expect, which might have unforeseen consequences (wrongly produced data etc). So I would at least do an additional warning here or even error out as multiple readers of the same name should not be allowed as this should not happen too often and can simply be solved by uninstalling one of the reader plugins.

I also have the same feeling for this. The code that picks up our readers has a clear priority that it will take the first one it sees. That can be annoying to debug as well. Then I will say let's throw an error at the very top of any invokation of our pipeline. So top level import/cli run. That way the user knows something is wrong in their setup. A warning might not be enough? What do you guys think?

**Comment by rettigl** [comment]
> I also have the same feeling for this. The code that picks up our readers has a clear priority that it will take the first one it sees. That can be annoying to debug as well. Then I will say let's throw an error at the very top of any invokation of our pipeline. So top level import/cli run. That way the user knows something is wrong in their setup. A warning might not be enough? What do you guys think?

I agree, but it would be good to include some hints on how to fix the issue in the error message.

**Comment by domna** [comment]
I agree with both of your points, I think we should

- Emit an error message when we have readers with the same name
- Explain that this is due to incompatible plugins and also display their package names. We can then tell the user that they need to uninstall one of them for pynx to work again

**Comment by RubelMozumder** [comment]
> I agree with both of your points, I think we should
> 
> * Emit an error message when we have readers with the same name
> * Explain that this is due to incompatible plugins and also display their package names. We can then tell the user that they need to uninstall one of them for pynx to work again


I also see the value of the error message. Actually, the duplication was coming from the third part plugin which has another version of `nomad-lab` as a dependency. And that `nomad-lab` is the older one that brings the `pynxtools` reader in a subdirectory. So, in the error message, we can add this as a sort of possible reason for error.

**Comment by RubelMozumder** [comment]
It is resolved by @domna in another PR.

**Pull request closed without merging**
