### PR TITLE
Write NXroot attributes

### LINKED ISSUE #163: Write NXroot attributes
Currently, pynxtools does not write any attributes to NXroot. This should be supported, especially dealing with the `@partial` attribute for partial appdefs (see [here](https://github.com/FAIRmat-NFDI/data-modeling/blob/main/mpes/meetings/2023-10-18_nexus_defs_versioning.md#todos))

### PR DESCRIPTION
**Pull request by sherjeelshabih**
Fixes #163.

This allows the Template to now accept NXroot level NXobjects. I have made a test with /@default. 

Note: This makes the undocmuented warning test do nothing.

### CODE REVIEW

**Comment by domna** [comment]
We should also add the standard NXroot attributes here:
- [ ] file_time
- [ ] file_name
- [ ] file_update_time
- [ ] NeXus_version (related to #162, so we should maybe add it there)
- [ ] HDF_version
- [ ] HDF5_Version
- [ ] XML_version
- [ ] h5py_version
- ~[X] creator~ (We actually have something in entry for NXmpes - maybe we leave this out as this is not pynxtools specific?)
- ~[X] creator_version~

**Comment by sherjeelshabih** [comment]
> * [x]  file_time
> * [x]  file_name
> * [x]  file_update_time
> * [x]  HDF5_Version
> * [x]  h5py_version

I'll add NeXus_version once you're stable with #162 
> * [ ]  NeXus_version (related to [Add versioning for nexus_definitions #162](https://github.com/FAIRmat-NFDI/pynxtools/issues/162), so we should maybe add it there)

These don't work for us. The first is the hdf4 version. And we don't write any XML here.
> * [ ]  HDF_version
> * [ ]  XML_version

**Comment by domna** [comment]
This works fine for me, however I get undocumented field warnings when I execute this on my example files:

```
❯ dataconverter --reader mpes --nxdl NXmpes --input-file MoTe2.h5 --input-file config_file.json --output MoTe2.mpes.nxs --undocumented
Using mpes reader to convert the given files:  
• MoTe2.h5
• config_file.json 
The path, /@NX_class, is being written but has no documentation.
The path, /@file_name, is being written but has no documentation.
The path, /@file_time, is being written but has no documentation.
The path, /@file_update_time, is being written but has no documentation.
The path, /@NeXus_version, is being written but has no documentation.
The path, /@HDF5_version, is being written but has no documentation.
The path, /@h5py_version, is being written but has no documentation.
The output file generated: MoTe2.mpes.nxs
```

Interestingly, I don't get an undocumented warning for `@partial` if I add it to NXroot...

**Comment by sherjeelshabih** [comment]
> This works fine for me, however I get undocumented field warnings when I execute this on my example files:
> 
> ```
> ❯ dataconverter --reader mpes --nxdl NXmpes --input-file MoTe2.h5 --input-file config_file.json --output MoTe2.mpes.nxs --undocumented
> Using mpes reader to convert the given files:  
> • MoTe2.h5
> • config_file.json 
> The path, /@NX_class, is being written but has no documentation.
> The path, /@file_name, is being written but has no documentation.
> The path, /@file_time, is being written but has no documentation.
> The path, /@file_update_time, is being written but has no documentation.
> The path, /@NeXus_version, is being written but has no documentation.
> The path, /@HDF5_version, is being written but has no documentation.
> The path, /@h5py_version, is being written but has no documentation.
> The output file generated: MoTe2.mpes.nxs
> ```
> 
> Interestingly, I don't get an undocumented warning for `@partial` if I add it to NXroot...

The NXroot objects are not added during Template generation. This means when I add them, they get added to the undocumented part of the Template. I don't want to re-run them and figure out their validity. It's too expensive. Here, we know that the code is producing them correctly anyways. So I just skip over those checks. 

Now, you won't get the undocumented warnings.

**Review by domna — APPROVED** [review]
Works perfect now :)
I can also add the `NeXus_version` attribute in #162 if you want to merge this already.

**Pull request merged**
