### PR TITLE
Adds stm extra install to pyproject.toml

### PR DESCRIPTION
**Pull request by domna**

### CODE REVIEW

**Comment by lukaspie** [comment]
LGTM. I guess you guys fixed the git dependency in pynxtools-stm?

**Review by lukaspie — APPROVED** [review]

**Comment by domna** [comment]
> LGTM. I guess you guys fixed the git dependency in pynxtools-stm?

I just made the dependency a submodule 😬

**Comment by lukaspie** [comment]
> > LGTM. I guess you guys fixed the git dependency in pynxtools-stm?
> 
> I just made the dependency a submodule 😬

Ok, a bit ugly, but as long as it work :D

**Comment by RubelMozumder** [comment]
I have removed the `nanonispy` as submodule but brought the code from that repo with the git history.
LGTM!

**Review by RubelMozumder — APPROVED** [review]
All should work perfectly!

**Pull request merged**
